[book]
title = "Computer Science"
language = "it"
description = "Appunti per il corso di Informatica all'Università di Venezia"
src = "src"

[build]
use-default-preprocessors = false	# Disable index to fix issue #431

[preprocessor.links]

[preprocessor.katex]

[preprocessor.graphviz]

[output.html]
preferred-dark-theme = "light"
no-section-label = false
additional-css = ["book.css"]
mathjax-support = false

[output.html.fold]
enable = true

[output.html.print]
enable = false
