[book]
title = "Computer Science"
language = "it"
description = "Appunti per il corso di Informatica all'Università di Venezia"
src = "src"

[preprocessor.katex]

[output.html]
no-section-label = true
additional-css = ["book.css"]
mathjax-support = true

[output.html.fold]
enable = true

[output.html.print]
enable = false

[output.katex]
