[package]
name = "mdbook-dot"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = {version = "0.4.40", default-features = false}
serde_json = "1.0.128"
rayon = "1.10.0"
regex = "1.10.6"
base64 = "0.22.1"
