name: mdbook-build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.40'

      - name: Setup Graphviz
        run: |
          wget 'https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/12.1.1/ubuntu_22.04_graphviz-12.1.1-debs.tar.xz'
          tar -xvf ubuntu_22.04_graphviz-12.1.1-debs.tar.xz
          sudo apt-get install -y fonts-liberation ./graphviz_12.1.1-1_amd64.deb ./libgraphviz4_12.1.1-1_amd64.deb

      - name: Download the katex preprocessor
        run: |
          wget 'https://github.com/lzanini/mdbook-katex/releases/download/0.9.0-binaries/mdbook-katex-v0.9.0-x86_64-unknown-linux-gnu.tar.gz'
          tar -xvf mdbook-katex-v0.9.0-x86_64-unknown-linux-gnu.tar.gz
          mv -v mdbook-katex ~/.cargo/bin

      - name: Build the dot preprocessor
        run: |
          cargo build --manifest-path deps/mdbook-dot/Cargo.toml
          cp deps/mdbook-dot/target/debug/mdbook-dot ~/.cargo/bin

      - name: Build the book files
        run: mdbook build

      - name: Deploy to the GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./book
          publish_branch: book
