name: mdbook-build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.21'

      - name: Download the katex preprocessor
        run: |
          wget 'https://github.com/lzanini/mdbook-katex/releases/download/v0.2.17/mdbook-katex-v0.2.17-x86_64-unknown-linux-gnu.tar.gz'
          tar xvf mdbook-katex-v0.2.17-x86_64-unknown-linux-gnu.tar.gz
          mv -v mdbook-katex ~/.cargo/bin

      - name: Build the book files
        run: mdbook build

      - name: Deploy to the GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./book/html
          publish_branch: book
